[env:esp32-s3-amoled-191]
platform = espressif32
board = esp32-s3-amoled-191
framework = arduino

upload_port = /dev/cu.usbmodem2101
monitor_port = /dev/cu.usbmodem2101
monitor_speed = 115200

lib_deps =
  moononournation/GFX Library for Arduino@1.5.6
