#pragma once

#include <Arduino.h>

struct GuiBootPhase {
    const char* name;
    const char* script;
};

const char fifthos_gui_boot_phase1[] =
R"FIFTH(
\ FifthOS foundation vocabulary

HEX
0000 CONSTANT BLACK
FFFF CONSTANT WHITE
F800 CONSTANT RED
07E0 CONSTANT GREEN
001F CONSTANT BLUE
7DFF CONSTANT ICE
3A8F CONSTANT ICE-DIM
1290 CONSTANT ICE-LOW
FD20 CONSTANT ORANGE
7BEF CONSTANT GRAY
39E7 CONSTANT DARK-GRAY
1082 CONSTANT INK-1
2104 CONSTANT INK-2
4208 CONSTANT INK-3
DECIMAL

: 0= 0 = ;

VARIABLE G0
VARIABLE G1
VARIABLE G2
VARIABLE G3
VARIABLE G4
VARIABLE G5
VARIABLE G6
VARIABLE G7
VARIABLE G8
VARIABLE G9

: DROP5 DROP DROP DROP DROP DROP ;

: CENTER-TEXT
  G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G3 @ G4 @ TEXT-W G2 @ SWAP - 2/ G0 @ +
  G1 @ G3 @ G4 @ G5 @ TEXT ;

: RIGHT-TEXT
  G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G3 @ G4 @ TEXT-W G2 @ SWAP - G0 @ +
  G1 @ G3 @ G4 @ G5 @ TEXT ;

: BORDER RECT ;

: PANEL
  G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ G2 @ G3 @ G4 @ FILL-RECT
  G0 @ G1 @ G2 @ G3 @ G5 @ RECT ;

: LABEL TEXT ;

: STATUS-BAR
  G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ G2 @ G3 @ G7 @ FILL-RECT
  G0 @ G1 @ G2 @ G4 @ G5 @ G6 @ CENTER-TEXT ;

: PROGRESS-BAR
  G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ G2 @ G3 @ G7 @ FILL-RECT
  G0 @ G1 @ G4 @ G2 @ G5 @ */ G3 @ G6 @ FILL-RECT ;

: HLINE
  G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ G0 @ G2 @ + G1 @ G3 @ LINE ;

: VLINE
  G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ G0 @ G1 @ G2 @ + G3 @ LINE ;

: CLEAR-REGION FILL-RECT ;
: INSET-RECT >R R@ + SWAP R@ + SWAP R@ 2* - SWAP R> 2* - ;

0 CONSTANT STYLE>FG
1 CONSTANT STYLE>BG
2 CONSTANT STYLE>BORDER
3 CONSTANT STYLE>PADDING
4 CONSTANT STYLE>FONT

0 CONSTANT NODE>PARENT
1 CONSTANT NODE>FIRST
2 CONSTANT NODE>NEXT
3 CONSTANT NODE>X
4 CONSTANT NODE>Y
5 CONSTANT NODE>W
6 CONSTANT NODE>H
7 CONSTANT NODE>FLAGS
8 CONSTANT NODE>DRAW
9 CONSTANT NODE>EVENT
10 CONSTANT NODE>STYLE
11 CONSTANT NODE>USER
12 CONSTANT NODE>KIND
13 CONSTANT NODE>TEXT
14 CONSTANT NODE>TEXTLEN
15 CONSTANT NODE>BIND
16 CONSTANT NODE>MIN
17 CONSTANT NODE>MAX
18 CONSTANT NODE>POINTS
19 CONSTANT NODE>COUNT

1 CONSTANT NODE.VISIBLE
2 CONSTANT NODE.DIRTY.FLAG
4 CONSTANT NODE.TOUCHABLE
8 CONSTANT NODE.FOCUSABLE

: STYLE.MAKE STYLE.NEW DUP >R STYLE.SET R> ;

: STYLE.FG STYLE>FG STYLE.FIELD@ ;
: STYLE.BG STYLE>BG STYLE.FIELD@ ;
: STYLE.BORDER STYLE>BORDER STYLE.FIELD@ ;

: NODE.DRAW! NODE>DRAW NODE.FIELD! ;
: NODE.EVENT! NODE>EVENT NODE.FIELD! ;
: NODE.STYLE! NODE>STYLE NODE.FIELD! ;
: NODE.COLOR NODE>STYLE NODE.FIELD@ STYLE.FG ;

: SCREEN.NEW
  G0 !
  NODE.NEW DUP G1 !
  0 0 SCREEN.W SCREEN.H G1 @ NODE.SET-BOUNDS
  NODE.VISIBLE NODE.DIRTY.FLAG OR NODE.TOUCHABLE OR G1 @ NODE>FLAGS NODE.FIELD!
  G0 @ G1 @ NODE>STYLE NODE.FIELD!
  G1 @ ;

: DRAW.NODE
  G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  NODE.NEW DUP G7 !
  G0 @ G7 @ NODE.ADD
  G6 @ G7 @ NODE.DRAW!
  G5 @ G7 @ NODE.STYLE!
  G1 @ G2 @ G3 @ G4 @ G7 @ NODE.SET-BOUNDS
  G7 @ ;

: GUI.PANEL W.PANEL ;
: GUI.LABEL W.LABEL ;
: GUI.BUTTON W.BUTTON ;
: GUI.STATUS W.STATUS ;
: GUI.VALUE W.VALUE ;
: GUI.GAUGE W.GAUGE ;
: GUI.CHART W.CHART ;
: GUI.ALARM W.ALARM ;
: GUI.ICON16 W.ICON16 ;
: ICON.1BIT BITMAP1 ;

: TOUCH.DEBUG
  TOUCH.UPDATE DROP
  ." touch type=" TOUCH.TYPE .
  ." x=" TOUCH.X .
  ." y=" TOUCH.Y .
  ." dx=" TOUCH.DX .
  ." dy=" TOUCH.DY . CR ;

: PUT2
  >R
  10 /MOD DIGIT R@ C!
  DIGIT R> 1+ C! ;
)FIFTH";

const char fifthos_gui_boot_phase2[] =
R"FIFTH(
\ FifthOS generic UI kit

12 CONSTANT GAP
12 CONSTANT EDGE
40 CONSTANT CONTENT.Y

: FACE.X EDGE ;
: FACE.W SCREEN.W EDGE 2* - ;
: FACE.H SCREEN.H ;
: CONTENT.H SCREEN.H CONTENT.Y - ;
: HALF.W FACE.W GAP - 2/ ;
: RIGHT.X HALF.W GAP + ;

VARIABLE STYLE.ROOT
VARIABLE STYLE.RAIL
VARIABLE STYLE.NAV.IDLE
VARIABLE STYLE.NAV.ACTIVE
VARIABLE STYLE.TITLE
VARIABLE STYLE.SUB
VARIABLE STYLE.CARD
VARIABLE STYLE.HERO
VARIABLE STYLE.MUTED
VARIABLE STYLE.ACCENT
VARIABLE STYLE.ALERT
VARIABLE STYLE.BUTTON
VARIABLE STYLE.METRIC
VARIABLE STYLE.NAV.TEXT
VARIABLE STYLE.BIG
VARIABLE STYLE.RIBBON
VARIABLE STYLE.CLOCK.TIME
VARIABLE STYLE.CLOCK.SEC
VARIABLE STYLE.CLOCK.INFO

: FACE.PANEL
  G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ FACE.X G1 @ + G2 @ G3 @ G4 @ G5 @ GUI.PANEL ;

: FACE.LABEL
  G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ FACE.X G1 @ + G2 @ G3 @ G4 @ G5 @ G6 @ G7 @ GUI.LABEL ;

: FACE.BUTTON
  G8 ! G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ FACE.X G1 @ + G2 @ G3 @ G4 @ G5 @ G6 @ G7 @ G8 @ GUI.BUTTON ;

: FACE.VALUE
  G8 ! G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ FACE.X G1 @ + G2 @ G3 @ G4 @ G5 @ G6 @ G7 @ G8 @ GUI.VALUE ;

: FACE.STATUS
  G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ FACE.X G1 @ + G2 @ G3 @ G4 @ G5 @ G6 @ G7 @ GUI.STATUS ;

: FACE.GAUGE
  G8 ! G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ FACE.X G1 @ + G2 @ G3 @ G4 @ G5 @ G6 @ G7 @ G8 @ GUI.GAUGE ;

: FACE.CHART
  G9 ! G8 ! G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ FACE.X G1 @ + G2 @ G3 @ G4 @ G5 @ G6 @ G7 @ G8 @ G9 @ GUI.CHART ;

: FACE.ALARM
  G8 ! G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ FACE.X G1 @ + G2 @ G3 @ G4 @ G5 @ G6 @ G7 @ G8 @ GUI.ALARM ;

: FACE.ICON
  G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ FACE.X G1 @ + G2 @ G3 @ G4 @ G5 @ GUI.ICON16 ;

: SCREEN.TITLE
  DROP DROP DROP ;

: SCREEN.SUBTITLE
  DROP DROP DROP ;

: NAV.STYLE = IF STYLE.NAV.ACTIVE @ ELSE STYLE.NAV.IDLE @ THEN ;

: BUILD.SHELL
  G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  DROP DROP DROP DROP DROP DROP ;

: FACE.RULE
  G1 ! G0 !
  G0 @ 0 G1 @ FACE.W 1 STYLE.ACCENT @ FACE.PANEL DROP ;

: FACE.BOX
  G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ G2 @ G3 @ BLACK G4 @ PANEL ;

: FACE.INVERT
  G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ FACE.X G1 @ + G2 @ G3 @ G7 @ GUI.PANEL DROP
  G0 @ FACE.X G1 @ + G2 @ G3 @ G4 @ G5 @ G6 @ BLACK GUI.LABEL DROP ;

CREATE ICON.RAIN.DATA
HEX
03C0 , 07E0 , 0E70 , 1C38 ,
1C38 , 3FFC , 7FFE , 7FFE ,
3FFC , 0630 , 0C18 , 0630 ,
0C18 , 0000 , 0000 , 0000 ,
DECIMAL

: ICON.RAIN
  G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ 16 16 G2 @ G3 @ ICON.RAIN.DATA ICON.1BIT ;

CREATE ICON.CLOCK.DATA
HEX
03C0 , 0FF0 , 1C38 , 300C ,
67E6 , 6C36 , 6C36 , 6FF6 ,
6C36 , 6C36 , 300C , 1C38 ,
0FF0 , 03C0 , 0000 , 0000 ,
DECIMAL

: ICON.CLOCK
  G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ 16 16 G2 @ G3 @ ICON.CLOCK.DATA ICON.1BIT ;

CREATE ICON.CALENDAR.DATA
HEX
7FFE , 6006 , 6C36 , 6C36 ,
7FFE , 6006 , 6F66 , 6F66 ,
6F66 , 6F66 , 6F66 , 6F66 ,
6006 , 7FFE , 0000 , 0000 ,
DECIMAL

: ICON.CALENDAR
  G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ 16 16 G2 @ G3 @ ICON.CALENDAR.DATA ICON.1BIT ;

CREATE ICON.ALARM.DATA
HEX
0180 , 03C0 , 0C30 , 1818 ,
300C , 300C , 300C , 3FFC ,
3FFC , 0FF0 , 03C0 , 03C0 ,
0180 , 0300 , 0000 , 0000 ,
DECIMAL

: ICON.ALARM
  G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ 16 16 G2 @ G3 @ ICON.ALARM.DATA ICON.1BIT ;

: ADD.NAV.CLOCK
  G0 !
  G0 @ 96 6 STYLE.NAV.ACTIVE @ ICON.CLOCK.DATA 2 FACE.ICON DROP
  G0 @ 166 6 STYLE.NAV.IDLE @ ICON.CALENDAR.DATA 2 FACE.ICON DROP
  G0 @ 236 6 STYLE.NAV.IDLE @ ICON.ALARM.DATA 2 FACE.ICON DROP
  G0 @ 306 6 STYLE.NAV.IDLE @ ICON.RAIN.DATA 2 FACE.ICON DROP ;

: ADD.NAV.CALENDAR
  G0 !
  G0 @ 96 6 STYLE.NAV.IDLE @ ICON.CLOCK.DATA 2 FACE.ICON DROP
  G0 @ 166 6 STYLE.NAV.ACTIVE @ ICON.CALENDAR.DATA 2 FACE.ICON DROP
  G0 @ 236 6 STYLE.NAV.IDLE @ ICON.ALARM.DATA 2 FACE.ICON DROP
  G0 @ 306 6 STYLE.NAV.IDLE @ ICON.RAIN.DATA 2 FACE.ICON DROP ;

: ADD.NAV.ALARMS
  G0 !
  G0 @ 96 6 STYLE.NAV.IDLE @ ICON.CLOCK.DATA 2 FACE.ICON DROP
  G0 @ 166 6 STYLE.NAV.IDLE @ ICON.CALENDAR.DATA 2 FACE.ICON DROP
  G0 @ 236 6 STYLE.NAV.ACTIVE @ ICON.ALARM.DATA 2 FACE.ICON DROP
  G0 @ 306 6 STYLE.NAV.IDLE @ ICON.RAIN.DATA 2 FACE.ICON DROP ;

: ADD.NAV.WEATHER
  G0 !
  G0 @ 96 6 STYLE.NAV.IDLE @ ICON.CLOCK.DATA 2 FACE.ICON DROP
  G0 @ 166 6 STYLE.NAV.IDLE @ ICON.CALENDAR.DATA 2 FACE.ICON DROP
  G0 @ 236 6 STYLE.NAV.IDLE @ ICON.ALARM.DATA 2 FACE.ICON DROP
  G0 @ 306 6 STYLE.NAV.ACTIVE @ ICON.RAIN.DATA 2 FACE.ICON DROP ;

: ADD.WEATHER.BADGE
  G0 !
  G0 @ 294 58 STYLE.TITLE @ ICON.RAIN.DATA 2 FACE.ICON DROP ;
)FIFTH";

const char fifthos_gui_boot_phase3[] =
R"FIFTH(
\ FifthOS app state and callbacks

VARIABLE FIFTH.APP
VARIABLE SCREEN.CLOCK
VARIABLE SCREEN.CALENDAR
VARIABLE SCREEN.ALARMS
VARIABLE SCREEN.WEATHER
VARIABLE TASK.CLOCK
VARIABLE NODE.CLOCK.HH
VARIABLE NODE.CLOCK.MM
VARIABLE NODE.CLOCK.SS
VARIABLE NODE.CLOCK.INFO
VARIABLE CLOCK.HOUR
VARIABLE CLOCK.MINUTE
VARIABLE CLOCK.SECOND
VARIABLE CLOCK.DAY
VARIABLE CLOCK.MONTH
VARIABLE CLOCK.YEAR
VARIABLE CLOCK.WDAY

VARIABLE CLOCK.FOCUS
VARIABLE ALARM.ARMED
VARIABLE WEATHER.TEMP
VARIABLE WEATHER.WIND
VARIABLE WEATHER.HUM

HERE 8 ALLOT CONSTANT CLOCK.TIME.BUF
HERE 2 ALLOT CONSTANT CLOCK.HH.BUF
HERE 2 ALLOT CONSTANT CLOCK.MM.BUF
HERE 2 ALLOT CONSTANT CLOCK.SS.BUF
HERE 1 ALLOT CONSTANT CLOCK.COLON.BUF
HERE 10 ALLOT CONSTANT CLOCK.DATE.BUF
HERE 3 ALLOT CONSTANT CLOCK.WDAY.BUF
HERE 14 ALLOT CONSTANT CLOCK.INFO.BUF

73 CLOCK.FOCUS !
1 ALARM.ARMED !
18 WEATHER.TEMP !
14 WEATHER.WIND !
67 WEATHER.HUM !
0 TASK.CLOCK !
58 CLOCK.COLON.BUF C!

CREATE WEATHER.TREND 8 CELLS ALLOT
16 WEATHER.TREND !
17 WEATHER.TREND CELL+ !
18 WEATHER.TREND CELL+ CELL+ !
20 WEATHER.TREND 3 CELLS + !
22 WEATHER.TREND 4 CELLS + !
21 WEATHER.TREND 5 CELLS + !
19 WEATHER.TREND 6 CELLS + !
18 WEATHER.TREND 7 CELLS + !

: NAV.TAP?
  G4 ! G3 ! G2 ! G1 ! G0 !
  G1 @ TOUCH.TAP = ;

: SHOW.CLOCK NAV.TAP? IF FIFTH.APP @ 0 APP.SHOW THEN ;
' SHOW.CLOCK CONSTANT SHOW.CLOCK.XT

: SHOW.CALENDAR NAV.TAP? IF FIFTH.APP @ 1 APP.SHOW THEN ;
' SHOW.CALENDAR CONSTANT SHOW.CALENDAR.XT

: SHOW.ALARMS NAV.TAP? IF FIFTH.APP @ 2 APP.SHOW THEN ;
' SHOW.ALARMS CONSTANT SHOW.ALARMS.XT

: SHOW.WEATHER NAV.TAP? IF FIFTH.APP @ 3 APP.SHOW THEN ;
' SHOW.WEATHER CONSTANT SHOW.WEATHER.XT

: HANDLE.NAV.TAP
  NAV.TAP? IF
    G3 @ 40 < IF
      G2 @ 96  < 0= G2 @ 128 < AND IF FIFTH.APP @ 0 APP.SHOW THEN
      G2 @ 166 < 0= G2 @ 198 < AND IF FIFTH.APP @ 1 APP.SHOW THEN
      G2 @ 236 < 0= G2 @ 268 < AND IF FIFTH.APP @ 2 APP.SHOW THEN
      G2 @ 306 < 0= G2 @ 338 < AND IF FIFTH.APP @ 3 APP.SHOW THEN
    THEN
  THEN ;
' HANDLE.NAV.TAP CONSTANT HANDLE.NAV.TAP.XT

: TOGGLE.ALARM
  NAV.TAP? IF
    ALARM.ARMED @ 0= IF 1 ELSE 0 THEN ALARM.ARMED !
    SCREEN.ALARMS @ NODE.DIRTY
  THEN ;
' TOGGLE.ALARM CONSTANT TOGGLE.ALARM.XT

: CLOCK.BUFFERS.UPDATE
  TIME.HMS G2 ! G1 ! G0 !
  G0 @ CLOCK.HH.BUF PUT2
  G1 @ CLOCK.MM.BUF PUT2
  G2 @ CLOCK.SS.BUF PUT2
  G0 @ CLOCK.TIME.BUF PUT2
  58 CLOCK.TIME.BUF 2 + C!
  G1 @ CLOCK.TIME.BUF 3 + PUT2
  58 CLOCK.TIME.BUF 5 + C!
  G2 @ CLOCK.TIME.BUF 6 + PUT2 ;

: CLOCK.DATE.UPDATE
  TIME.YMD G2 ! G1 ! G0 !
  G2 @ CLOCK.DATE.BUF PUT2
  47 CLOCK.DATE.BUF 2 + C!
  G1 @ CLOCK.DATE.BUF 3 + PUT2
  47 CLOCK.DATE.BUF 5 + C!
  G0 @ 1000 / DIGIT CLOCK.DATE.BUF 6 + C!
  G0 @ 1000 MOD 100 / DIGIT CLOCK.DATE.BUF 7 + C!
  G0 @ 100 MOD 10 / DIGIT CLOCK.DATE.BUF 8 + C!
  G0 @ 10 MOD DIGIT CLOCK.DATE.BUF 9 + C!
  TIME.WDAY G4 !
  G4 @ 0 = IF 83 CLOCK.INFO.BUF 0 + C! 85 CLOCK.INFO.BUF 1 + C! 78 CLOCK.INFO.BUF 2 + C! THEN
  G4 @ 1 = IF 77 CLOCK.INFO.BUF 0 + C! 79 CLOCK.INFO.BUF 1 + C! 78 CLOCK.INFO.BUF 2 + C! THEN
  G4 @ 2 = IF 84 CLOCK.INFO.BUF 0 + C! 85 CLOCK.INFO.BUF 1 + C! 69 CLOCK.INFO.BUF 2 + C! THEN
  G4 @ 3 = IF 87 CLOCK.INFO.BUF 0 + C! 69 CLOCK.INFO.BUF 1 + C! 68 CLOCK.INFO.BUF 2 + C! THEN
  G4 @ 4 = IF 84 CLOCK.INFO.BUF 0 + C! 72 CLOCK.INFO.BUF 1 + C! 85 CLOCK.INFO.BUF 2 + C! THEN
  G4 @ 5 = IF 70 CLOCK.INFO.BUF 0 + C! 82 CLOCK.INFO.BUF 1 + C! 73 CLOCK.INFO.BUF 2 + C! THEN
  G4 @ 6 = IF 83 CLOCK.INFO.BUF 0 + C! 65 CLOCK.INFO.BUF 1 + C! 84 CLOCK.INFO.BUF 2 + C! THEN
  32 CLOCK.INFO.BUF 3 + C!
  CLOCK.DATE.BUF C@ CLOCK.INFO.BUF 4 + C!
  CLOCK.DATE.BUF 1+ C@ CLOCK.INFO.BUF 5 + C!
  CLOCK.DATE.BUF 2 + C@ CLOCK.INFO.BUF 6 + C!
  CLOCK.DATE.BUF 3 + C@ CLOCK.INFO.BUF 7 + C!
  CLOCK.DATE.BUF 4 + C@ CLOCK.INFO.BUF 8 + C!
  CLOCK.DATE.BUF 5 + C@ CLOCK.INFO.BUF 9 + C!
  CLOCK.DATE.BUF 6 + C@ CLOCK.INFO.BUF 10 + C!
  CLOCK.DATE.BUF 7 + C@ CLOCK.INFO.BUF 11 + C!
  CLOCK.DATE.BUF 8 + C@ CLOCK.INFO.BUF 12 + C!
  CLOCK.DATE.BUF 9 + C@ CLOCK.INFO.BUF 13 + C! ;

: CLOCK.REFRESH
  TIME.HMS G2 ! G1 ! G0 !
  G0 @ CLOCK.HOUR @ = 0= IF
    G0 @ CLOCK.HOUR !
    G0 @ CLOCK.HH.BUF PUT2
    NODE.CLOCK.HH @ NODE.DIRTY
  THEN
  G1 @ CLOCK.MINUTE @ = 0= IF
    G1 @ CLOCK.MINUTE !
    G1 @ CLOCK.MM.BUF PUT2
    NODE.CLOCK.MM @ NODE.DIRTY
  THEN
  G2 @ CLOCK.SECOND @ = 0= IF
    G2 @ CLOCK.SECOND !
    G2 @ CLOCK.SS.BUF PUT2
    NODE.CLOCK.SS @ NODE.DIRTY
  THEN
  G0 @ CLOCK.TIME.BUF PUT2
  58 CLOCK.TIME.BUF 2 + C!
  G1 @ CLOCK.TIME.BUF 3 + PUT2
  58 CLOCK.TIME.BUF 5 + C!
  G2 @ CLOCK.TIME.BUF 6 + PUT2
  TIME.YMD G2 ! G1 ! G0 !
  TIME.WDAY G3 !
  G2 @ CLOCK.DAY @ = 0=
  G1 @ CLOCK.MONTH @ = 0= OR
  G0 @ CLOCK.YEAR @ = 0= OR
  G3 @ CLOCK.WDAY @ = 0= OR
  IF
    G2 @ CLOCK.DAY !
    G1 @ CLOCK.MONTH !
    G0 @ CLOCK.YEAR !
    G3 @ CLOCK.WDAY !
    CLOCK.DATE.UPDATE
    NODE.CLOCK.INFO @ NODE.DIRTY
  THEN ;
' CLOCK.REFRESH CONSTANT CLOCK.REFRESH.XT

: START.DATA.TASKS
  TASK.CLOCK @ ?DUP IF
    DUP G0 !
    TASK.STOP
    G0 @ 1000 CLOCK.REFRESH.XT TASK.EVERY
    G0 @ TASK.START
    EXIT
  THEN
  TASK.NEW DUP TASK.CLOCK ! DUP G0 !
  1000 CLOCK.REFRESH.XT TASK.EVERY
  G0 @ TASK.START ;

: DEMO.TICK
  G4 ! G3 ! G2 ! G1 ! G0 !
  G1 @ TIMER = IF
    CLOCK.FOCUS @ 3 + 100 MOD CLOCK.FOCUS !
    WEATHER.TEMP @ 1+ DUP 25 SWAP < IF DROP 17 THEN WEATHER.TEMP !
    WEATHER.WIND @ 1+ DUP 20 SWAP < IF DROP 11 THEN WEATHER.WIND !
    WEATHER.HUM @ 2 + DUP 86 SWAP < IF DROP 58 THEN WEATHER.HUM !
    SCREEN.WEATHER @ NODE.DIRTY
  THEN ;
' DEMO.TICK CONSTANT DEMO.TICK.XT

: ROOT.DRAW.CLOCK DROP ;
' ROOT.DRAW.CLOCK CONSTANT ROOT.DRAW.CLOCK.XT

: ROOT.DRAW.CALENDAR DROP ;
' ROOT.DRAW.CALENDAR CONSTANT ROOT.DRAW.CALENDAR.XT

: ROOT.DRAW.ALARMS DROP ;
' ROOT.DRAW.ALARMS CONSTANT ROOT.DRAW.ALARMS.XT

: ROOT.DRAW.WEATHER DROP ;
' ROOT.DRAW.WEATHER CONSTANT ROOT.DRAW.WEATHER.XT

: CLOCK.ROOT.EVENT
  HANDLE.NAV.TAP ;
' CLOCK.ROOT.EVENT CONSTANT CLOCK.ROOT.EVENT.XT

: SIMPLE.ROOT.EVENT
  HANDLE.NAV.TAP ;
' SIMPLE.ROOT.EVENT CONSTANT SIMPLE.ROOT.EVENT.XT

: WEATHER.ROOT.EVENT
  HANDLE.NAV.TAP
  DEMO.TICK ;
' WEATHER.ROOT.EVENT CONSTANT WEATHER.ROOT.EVENT.XT

: BUILD.STYLES
  ICE BLACK BLACK 0 1 STYLE.MAKE STYLE.ROOT !
  ICE BLACK BLACK 0 1 STYLE.MAKE STYLE.RAIL !
  GRAY BLACK BLACK 0 1 STYLE.MAKE STYLE.NAV.IDLE !
  WHITE BLACK BLACK 0 1 STYLE.MAKE STYLE.NAV.ACTIVE !
  ICE BLACK BLACK 0 2 STYLE.MAKE STYLE.TITLE !
  ICE-DIM BLACK BLACK 0 1 STYLE.MAKE STYLE.SUB !
  ICE-DIM BLACK ICE-DIM 2 1 STYLE.MAKE STYLE.CARD !
  ICE BLACK BLACK 0 5 STYLE.MAKE STYLE.HERO !
  ICE BLACK BLACK 0 8 STYLE.MAKE STYLE.CLOCK.TIME !
  ICE BLACK BLACK 0 6 STYLE.MAKE STYLE.CLOCK.SEC !
  ICE BLACK BLACK 0 3 STYLE.MAKE STYLE.CLOCK.INFO !
  ICE-LOW BLACK BLACK 0 1 STYLE.MAKE STYLE.MUTED !
  ICE BLACK ICE 2 1 STYLE.MAKE STYLE.ACCENT !
  ORANGE BLACK ORANGE 2 1 STYLE.MAKE STYLE.ALERT !
  BLACK ICE ICE 2 1 STYLE.MAKE STYLE.BUTTON !
  ICE BLACK ICE-DIM 2 2 STYLE.MAKE STYLE.METRIC !
  ICE BLACK BLACK 0 1 STYLE.MAKE STYLE.NAV.TEXT !
  ICE BLACK BLACK 0 3 STYLE.MAKE STYLE.BIG !
  BLACK ICE-DIM ICE-DIM 1 1 STYLE.MAKE STYLE.RIBBON ! ;
)FIFTH";

const char fifthos_gui_boot_phase4[] =
R"FIFTH(
\ FifthOS app screens

: ADD.NAV
  DROP DROP ;

: BUILD.CLOCK
  STYLE.ROOT @ SCREEN.NEW DUP SCREEN.CLOCK !
  ROOT.DRAW.CLOCK.XT SCREEN.CLOCK @ NODE.DRAW!
  CLOCK.ROOT.EVENT.XT SCREEN.CLOCK @ NODE.EVENT!
  SCREEN.CLOCK @ 0 $" CLOCK" COUNT $" LIVE FACE" COUNT BUILD.SHELL
  SCREEN.CLOCK @ ADD.NAV.CLOCK
  SCREEN.CLOCK @ 46 FACE.RULE
  SCREEN.CLOCK @ 32 88 120 92 STYLE.CLOCK.TIME @ CLOCK.HH.BUF 2 FACE.STATUS NODE.CLOCK.HH !
  SCREEN.CLOCK @ 146 88 24 92 STYLE.CLOCK.TIME @ CLOCK.COLON.BUF 1 FACE.STATUS DROP
  SCREEN.CLOCK @ 184 88 120 92 STYLE.CLOCK.TIME @ CLOCK.MM.BUF 2 FACE.STATUS NODE.CLOCK.MM !
  SCREEN.CLOCK @ 298 88 24 92 STYLE.CLOCK.TIME @ CLOCK.COLON.BUF 1 FACE.STATUS DROP
  SCREEN.CLOCK @ 336 88 120 92 STYLE.CLOCK.TIME @ CLOCK.SS.BUF 2 FACE.STATUS NODE.CLOCK.SS !
  SCREEN.CLOCK @ 0 196 FACE.W 1 STYLE.ACCENT @ FACE.PANEL DROP
  SCREEN.CLOCK @ 0 212 FACE.W 24 STYLE.CLOCK.INFO @ CLOCK.INFO.BUF 14 FACE.STATUS NODE.CLOCK.INFO ! ;

: BUILD.CALENDAR
  STYLE.ROOT @ SCREEN.NEW DUP SCREEN.CALENDAR !
  ROOT.DRAW.CALENDAR.XT SCREEN.CALENDAR @ NODE.DRAW!
  SIMPLE.ROOT.EVENT.XT SCREEN.CALENDAR @ NODE.EVENT!
  SCREEN.CALENDAR @ 1 $" CALENDAR" COUNT $" DAY PLAN" COUNT BUILD.SHELL
  SCREEN.CALENDAR @ ADD.NAV.CALENDAR
  SCREEN.CALENDAR @ 40 FACE.RULE
  SCREEN.CALENDAR @ 8 54 64 12 STYLE.MUTED @ $" DATE" COUNT FACE.LABEL DROP
  SCREEN.CALENDAR @ 8 72 140 72 STYLE.HERO @ CLOCK.DATE.BUF 5 FACE.LABEL DROP
  SCREEN.CALENDAR @ 18 146 120 14 STYLE.TITLE @ $" TODAY" COUNT FACE.LABEL DROP
  SCREEN.CALENDAR @ 18 164 98 12 STYLE.SUB @ $" WEEK 13" COUNT FACE.LABEL DROP
  SCREEN.CALENDAR @ 168 56 120 12 STYLE.MUTED @ $" NEXT" COUNT FACE.LABEL DROP
  SCREEN.CALENDAR @ 168 76 260 34 STYLE.BIG @ CLOCK.TIME.BUF 5 FACE.LABEL DROP
  SCREEN.CALENDAR @ 168 112 224 14 STYLE.TITLE @ $" DESIGN REVIEW" COUNT FACE.LABEL DROP
  SCREEN.CALENDAR @ 168 130 180 12 STYLE.SUB @ $" LAB 2 / 45 MIN" COUNT FACE.LABEL DROP
  SCREEN.CALENDAR @ 0 178 FACE.W 1 STYLE.ACCENT @ FACE.PANEL DROP
  SCREEN.CALENDAR @ 0 188 216 34 STYLE.CARD @ FACE.BOX DROP
  SCREEN.CALENDAR @ 12 194 90 10 STYLE.MUTED @ $" LATER" COUNT FACE.LABEL DROP
  SCREEN.CALENDAR @ 12 204 166 14 STYLE.TITLE @ $" 13:00 WEATHER SYNC" COUNT FACE.LABEL DROP
  SCREEN.CALENDAR @ 240 188 216 34 STYLE.CARD @ FACE.BOX DROP
  SCREEN.CALENDAR @ 252 194 76 10 STYLE.MUTED @ $" THEN" COUNT FACE.LABEL DROP
  SCREEN.CALENDAR @ 252 204 154 14 STYLE.TITLE @ $" 18:45 DINNER" COUNT FACE.LABEL DROP ;

: BUILD.ALARMS
  STYLE.ROOT @ SCREEN.NEW DUP SCREEN.ALARMS !
  ROOT.DRAW.ALARMS.XT SCREEN.ALARMS @ NODE.DRAW!
  SIMPLE.ROOT.EVENT.XT SCREEN.ALARMS @ NODE.EVENT!
  SCREEN.ALARMS @ 2 $" ALARMS" COUNT $" READY SET" COUNT BUILD.SHELL
  SCREEN.ALARMS @ ADD.NAV.ALARMS
  SCREEN.ALARMS @ 40 FACE.RULE
  SCREEN.ALARMS @ 8 54 70 12 STYLE.MUTED @ $" NEXT" COUNT FACE.LABEL DROP
  SCREEN.ALARMS @ 8 74 190 72 STYLE.HERO @ $" 06:30" COUNT FACE.LABEL DROP
  SCREEN.ALARMS @ 226 58 72 12 STYLE.MUTED @ $" MODE" COUNT FACE.LABEL DROP
  SCREEN.ALARMS @ 226 76 96 18 STYLE.TITLE @ $" MON-FRI" COUNT FACE.LABEL DROP
  SCREEN.ALARMS @ 226 100 110 12 STYLE.SUB @ $" BEDROOM" COUNT FACE.LABEL DROP
  SCREEN.ALARMS @ 336 60 120 30 STYLE.ALERT @ $" ARMED" COUNT ALARM.ARMED FACE.ALARM DROP
  SCREEN.ALARMS @ 0 154 FACE.W 1 STYLE.ACCENT @ FACE.PANEL DROP
  SCREEN.ALARMS @ 0 166 216 24 STYLE.CARD @ FACE.BOX DROP
  SCREEN.ALARMS @ 12 172 156 12 STYLE.TITLE @ $" 07:15 STUDIO" COUNT FACE.LABEL DROP
  SCREEN.ALARMS @ 240 166 216 24 STYLE.CARD @ FACE.BOX DROP
  SCREEN.ALARMS @ 252 172 150 12 STYLE.TITLE @ $" 08:40 TRAINING" COUNT FACE.LABEL DROP
  SCREEN.ALARMS @ 120 198 216 24 STYLE.BUTTON @ $" TOGGLE ARM" COUNT TOGGLE.ALARM.XT FACE.BUTTON DROP ;

: BUILD.WEATHER
  STYLE.ROOT @ SCREEN.NEW DUP SCREEN.WEATHER !
  ROOT.DRAW.WEATHER.XT SCREEN.WEATHER @ NODE.DRAW!
  WEATHER.ROOT.EVENT.XT SCREEN.WEATHER @ NODE.EVENT!
  SCREEN.WEATHER @ 3 $" WEATHER" COUNT $" LOCAL OUTLOOK" COUNT BUILD.SHELL
  SCREEN.WEATHER @ ADD.NAV.WEATHER
  SCREEN.WEATHER @ 40 FACE.RULE
  SCREEN.WEATHER @ 8 54 96 12 STYLE.MUTED @ $" OUTSIDE" COUNT FACE.LABEL DROP
  SCREEN.WEATHER @ 8 74 172 72 STYLE.HERO @ $" 18C" COUNT FACE.LABEL DROP
  SCREEN.WEATHER @ 190 56 STYLE.TITLE @ ICON.RAIN.DATA 3 FACE.ICON DROP
  SCREEN.WEATHER @ 254 58 170 14 STYLE.TITLE @ $" LIGHT RAIN" COUNT FACE.LABEL DROP
  SCREEN.WEATHER @ 254 78 160 12 STYLE.SUB @ $" FEELS LIKE 16C" COUNT FACE.LABEL DROP
  SCREEN.WEATHER @ 254 98 160 12 STYLE.SUB @ $" MAX 30 / MIN 18" COUNT FACE.LABEL DROP
  SCREEN.WEATHER @ 0 154 FACE.W 1 STYLE.ACCENT @ FACE.PANEL DROP
  SCREEN.WEATHER @ 0 166 144 56 STYLE.CARD @ FACE.BOX DROP
  SCREEN.WEATHER @ 12 174 64 10 STYLE.MUTED @ $" HUMID" COUNT FACE.LABEL DROP
  SCREEN.WEATHER @ 12 190 80 20 STYLE.BIG @ $" 67" COUNT FACE.LABEL DROP
  SCREEN.WEATHER @ 156 166 144 56 STYLE.CARD @ FACE.BOX DROP
  SCREEN.WEATHER @ 168 174 58 10 STYLE.MUTED @ $" WIND" COUNT FACE.LABEL DROP
  SCREEN.WEATHER @ 168 190 86 20 STYLE.BIG @ $" 14K" COUNT FACE.LABEL DROP
  SCREEN.WEATHER @ 312 166 144 56 STYLE.CARD @ FACE.BOX DROP
  SCREEN.WEATHER @ 324 174 64 10 STYLE.MUTED @ $" RAIN" COUNT FACE.LABEL DROP
  SCREEN.WEATHER @ 324 190 80 20 STYLE.BIG @ $" 40%" COUNT FACE.LABEL DROP ;

: BUILD.APP
  APP.NEW DUP FIFTH.APP !
  DUP SCREEN.CLOCK @ APP.ADD-SCREEN
  DUP SCREEN.CALENDAR @ APP.ADD-SCREEN
  DUP SCREEN.ALARMS @ APP.ADD-SCREEN
  DUP SCREEN.WEATHER @ APP.ADD-SCREEN
  0 APP.SHOW ;
)FIFTH";

const char fifthos_gui_boot_phase5[] =
R"FIFTH(
\ FifthOS app bootstrap

: FIFTHOS.GUI
  GFX.INIT
  BUILD.STYLES
  CLOCK.BUFFERS.UPDATE
  CLOCK.DATE.UPDATE
  BUILD.CLOCK
  BUILD.CALENDAR
  BUILD.ALARMS
  BUILD.WEATHER
  BUILD.APP
  START.DATA.TASKS
  FIFTH.APP @ APP.DRAW
  ." FifthOS UI ready" CR ;

FIFTHOS.GUI
)FIFTH";

const GuiBootPhase fifthos_gui_boot_phases[] = {
    { "Phase 1/5: foundation", fifthos_gui_boot_phase1 },
    { "Phase 2/5: ui kit", fifthos_gui_boot_phase2 },
    { "Phase 3/5: app state", fifthos_gui_boot_phase3 },
    { "Phase 4/5: screens", fifthos_gui_boot_phase4 },
    { "Phase 5/5: bootstrap", fifthos_gui_boot_phase5 },
};

constexpr size_t fifthos_gui_boot_phase_count = sizeof(fifthos_gui_boot_phases) / sizeof(fifthos_gui_boot_phases[0]);
