#pragma once

#include <Arduino.h>

struct GuiBootPhase {
    const char* name;
    const char* script;
};

const char fifthos_gui_boot_phase1[] =
R"FIFTH(
\ FifthOS graphics and GUI vocabulary

HEX
0000 CONSTANT BLACK
FFFF CONSTANT WHITE
F800 CONSTANT RED
07E0 CONSTANT GREEN
001F CONSTANT BLUE
FD20 CONSTANT ORANGE
7BEF CONSTANT GRAY
39E7 CONSTANT DARK-GRAY
DECIMAL

: 0= 0 = ;

VARIABLE G0
VARIABLE G1
VARIABLE G2
VARIABLE G3
VARIABLE G4
VARIABLE G5
VARIABLE G6
VARIABLE G7

: CENTER-TEXT
  G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G3 @ G4 @ TEXT-W G2 @ SWAP - 2/ G0 @ +
  G1 @ G3 @ G4 @ G5 @ TEXT ;

: RIGHT-TEXT
  G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G3 @ G4 @ TEXT-W G2 @ SWAP - G0 @ +
  G1 @ G3 @ G4 @ G5 @ TEXT ;

: BORDER RECT ;

: PANEL
  G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ G2 @ G3 @ G4 @ FILL-RECT
  G0 @ G1 @ G2 @ G3 @ G5 @ RECT ;

: LABEL TEXT ;

: STATUS-BAR
  G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ G2 @ G3 @ G7 @ FILL-RECT
  G0 @ G1 @ G2 @ G4 @ G5 @ G6 @ CENTER-TEXT ;

: PROGRESS-BAR
  G7 ! G6 ! G5 ! G4 ! G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ G2 @ G3 @ G7 @ FILL-RECT
  G0 @ G1 @ G4 @ G2 @ G5 @ */ G3 @ G6 @ FILL-RECT ;

: HLINE
  G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ G0 @ G2 @ + G1 @ G3 @ LINE ;

: VLINE
  G3 ! G2 ! G1 ! G0 !
  G0 @ G1 @ G0 @ G1 @ G2 @ + G3 @ LINE ;

: CLEAR-REGION FILL-RECT ;
: INSET-RECT >R R@ + SWAP R@ + SWAP R@ 2* - SWAP R> 2* - ;

0 CONSTANT STYLE>FG
1 CONSTANT STYLE>BG
2 CONSTANT STYLE>BORDER
3 CONSTANT STYLE>PADDING
4 CONSTANT STYLE>FONT

0 CONSTANT NODE>PARENT
1 CONSTANT NODE>FIRST
2 CONSTANT NODE>NEXT
3 CONSTANT NODE>X
4 CONSTANT NODE>Y
5 CONSTANT NODE>W
6 CONSTANT NODE>H
7 CONSTANT NODE>FLAGS
8 CONSTANT NODE>DRAW
9 CONSTANT NODE>EVENT
10 CONSTANT NODE>STYLE
11 CONSTANT NODE>USER
12 CONSTANT NODE>KIND
13 CONSTANT NODE>TEXT
14 CONSTANT NODE>TEXTLEN
15 CONSTANT NODE>BIND
16 CONSTANT NODE>MIN
17 CONSTANT NODE>MAX
18 CONSTANT NODE>POINTS
19 CONSTANT NODE>COUNT

1 CONSTANT NODE.VISIBLE
2 CONSTANT NODE.DIRTY.FLAG
4 CONSTANT NODE.TOUCHABLE
8 CONSTANT NODE.FOCUSABLE

: STYLE.MAKE STYLE.NEW DUP >R STYLE.SET R> ;

: SCREEN.NEW
  G0 !
  NODE.NEW
  0 0 SCREEN.W SCREEN.H OVER NODE.SET-BOUNDS
  NODE.VISIBLE NODE.DIRTY.FLAG OR NODE.TOUCHABLE OR OVER NODE>FLAGS NODE.FIELD!
  G0 @ OVER NODE>STYLE NODE.FIELD! ;

: GUI.PANEL W.PANEL ;
: GUI.LABEL W.LABEL ;
: GUI.BUTTON W.BUTTON ;
: GUI.STATUS W.STATUS ;
: GUI.VALUE W.VALUE ;
: GUI.GAUGE W.GAUGE ;
: GUI.CHART W.CHART ;
: GUI.ALARM W.ALARM ;

: TOUCH.DEBUG
  TOUCH.UPDATE DROP
  ." touch type=" TOUCH.TYPE .
  ." x=" TOUCH.X .
  ." y=" TOUCH.Y .
  ." dx=" TOUCH.DX .
  ." dy=" TOUCH.DY . CR ;
)FIFTH";

const char fifthos_gui_boot_phase2[] =
R"FIFTH(
VARIABLE DEMO.TEMP
VARIABLE DEMO.PRESSURE
VARIABLE DEMO.ALARM
68 DEMO.TEMP !
42 DEMO.PRESSURE !
0 DEMO.ALARM !

CREATE DEMO.HISTORY 12 CELLS ALLOT
10 DEMO.HISTORY !
12 DEMO.HISTORY CELL+ !
14 DEMO.HISTORY CELL+ CELL+ !
18 DEMO.HISTORY 3 CELLS + !
19 DEMO.HISTORY 4 CELLS + !
22 DEMO.HISTORY 5 CELLS + !
25 DEMO.HISTORY 6 CELLS + !
24 DEMO.HISTORY 7 CELLS + !
21 DEMO.HISTORY 8 CELLS + !
20 DEMO.HISTORY 9 CELLS + !
17 DEMO.HISTORY 10 CELLS + !
14 DEMO.HISTORY 11 CELLS + !

VARIABLE FIFTH.APP
VARIABLE SCREEN.MAIN
VARIABLE SCREEN.ALARMS
VARIABLE SCREEN.SYSTEM

VARIABLE STYLE.ROOT
VARIABLE STYLE.PANEL
VARIABLE STYLE.ACCENT
VARIABLE STYLE.ALARM
VARIABLE STYLE.BUTTON
)FIFTH";

const char fifthos_gui_boot_phase3[] =
R"FIFTH(
: TOGGLE.ALARM
  DROP DROP DROP DROP DROP
  DEMO.ALARM @ 0= IF 1 ELSE 0 THEN DEMO.ALARM !
  SCREEN.ALARMS @ NODE.DIRTY ;
' TOGGLE.ALARM CONSTANT TOGGLE.ALARM.XT

: DEMO.TICK
  DROP DROP DROP DROP DROP
  TOUCH.TYPE TIMER = IF
    DEMO.TEMP @ 1+ 100 MOD DEMO.TEMP !
    DEMO.PRESSURE @ 3 + 100 MOD DEMO.PRESSURE !
    SCREEN.MAIN @ NODE.DIRTY
  THEN ;
' DEMO.TICK CONSTANT DEMO.TICK.XT

: BUILD.STYLES
  WHITE BLACK GRAY 4 1 STYLE.MAKE STYLE.ROOT !
  WHITE DARK-GRAY GRAY 4 1 STYLE.MAKE STYLE.PANEL !
  GREEN BLACK GREEN 4 1 STYLE.MAKE STYLE.ACCENT !
  WHITE RED WHITE 4 1 STYLE.MAKE STYLE.ALARM !
  WHITE BLUE WHITE 4 1 STYLE.MAKE STYLE.BUTTON ! ;
)FIFTH";

const char fifthos_gui_boot_phase4[] =
R"FIFTH(
: BUILD.MAIN
  STYLE.ROOT @ SCREEN.NEW DUP SCREEN.MAIN !
  DEMO.TICK.XT SCREEN.MAIN @ NODE>EVENT NODE.FIELD!
  SCREEN.MAIN @ 0 0 SCREEN.W 28 STYLE.ACCENT @ $" FifthOS / Telemetry" COUNT GUI.STATUS DROP
  SCREEN.MAIN @ 8 38 224 180 STYLE.PANEL @ GUI.PANEL DROP
  SCREEN.MAIN @ 18 54 204 24 STYLE.ROOT @ $" Temperature" COUNT GUI.LABEL DROP
  SCREEN.MAIN @ 18 84 204 32 STYLE.ROOT @ $" Temp" COUNT DEMO.TEMP GUI.VALUE DROP
  SCREEN.MAIN @ 18 126 48 84 STYLE.ACCENT @ DEMO.PRESSURE 0 100 GUI.GAUGE DROP
  SCREEN.MAIN @ 78 126 144 84 STYLE.PANEL @ DEMO.HISTORY 12 0 100 GUI.CHART DROP ;

: BUILD.ALARMS
  STYLE.ROOT @ SCREEN.NEW DUP SCREEN.ALARMS !
  SCREEN.ALARMS @ 0 0 SCREEN.W 28 STYLE.ALARM @ $" FifthOS / Alarms" COUNT GUI.STATUS DROP
  SCREEN.ALARMS @ 12 52 216 68 STYLE.ALARM @ $" ALARM" COUNT DEMO.ALARM GUI.ALARM DROP
  SCREEN.ALARMS @ 12 140 216 44 STYLE.BUTTON @ $" Toggle Alarm" COUNT TOGGLE.ALARM.XT GUI.BUTTON DROP ;

: BUILD.SYSTEM
  STYLE.ROOT @ SCREEN.NEW DUP SCREEN.SYSTEM !
  SCREEN.SYSTEM @ 0 0 SCREEN.W 28 STYLE.PANEL @ $" FifthOS / System" COUNT GUI.STATUS DROP
  SCREEN.SYSTEM @ 12 52 216 28 STYLE.ROOT @ $" Touch controller: FT3168" COUNT GUI.LABEL DROP
  SCREEN.SYSTEM @ 12 86 216 28 STYLE.ROOT @ $" Swipe left/right to switch screens" COUNT GUI.LABEL DROP
  SCREEN.SYSTEM @ 12 120 216 28 STYLE.ROOT @ $" Use TOUCH.DEBUG from the REPL" COUNT GUI.LABEL DROP ;

: BUILD.APP
  APP.NEW DUP FIFTH.APP !
  DUP SCREEN.MAIN @ APP.ADD-SCREEN
  DUP SCREEN.ALARMS @ APP.ADD-SCREEN
  DUP SCREEN.SYSTEM @ APP.ADD-SCREEN
  0 APP.SHOW ;
)FIFTH";

const char fifthos_gui_boot_phase5[] =
R"FIFTH(
: FIFTHOS.GUI
  GFX.INIT
  BUILD.STYLES
  BUILD.MAIN
  BUILD.ALARMS
  BUILD.SYSTEM
  BUILD.APP
  FIFTH.APP @ APP.DRAW
  ." FifthOS GUI ready" CR ;

FIFTHOS.GUI
)FIFTH";

const GuiBootPhase fifthos_gui_boot_phases[] = {
    { "Phase 1/5: helpers", fifthos_gui_boot_phase1 },
    { "Phase 2/5: state", fifthos_gui_boot_phase2 },
    { "Phase 3/5: callbacks", fifthos_gui_boot_phase3 },
    { "Phase 4/5: screens", fifthos_gui_boot_phase4 },
    { "Phase 5/5: build app", fifthos_gui_boot_phase5 },
};

constexpr size_t fifthos_gui_boot_phase_count = sizeof(fifthos_gui_boot_phases) / sizeof(fifthos_gui_boot_phases[0]);
