#pragma once

#include <Arduino.h>

/******************************************************************************/
/* PRIMITIVES                                                                 */
/******************************************************************************/

extern void (*primitives[126])(void);

const int as_nop = 0;
const int as_accept = 1;
const int as_qrx = 2;
const int as_txsto = 3;
const int as_docon = 4;
const int as_dolit = 5;
const int as_dolist = 6;
const int as_exit = 7;
const int as_execu = 8;
const int as_donext = 9;
const int as_qbran = 10;
const int as_bran = 11;
const int as_store = 12;
const int as_at = 13;
const int as_cstor = 14;
const int as_cat = 15;
const int as_rpat = 16;
const int as_rpsto = 17;
const int as_rfrom = 18;
const int as_rat = 19;
const int as_tor = 20;
const int as_spat = 21;
const int as_spsto = 22;
const int as_drop = 23;
const int as_dup = 24;
const int as_swap = 25;
const int as_over = 26;
const int as_zless = 27;
const int as_andd = 28;
const int as_orr = 29;
const int as_xorr = 30;
const int as_uplus = 31;
const int as_next = 32;
const int as_qdup = 33;
const int as_rot = 34;
const int as_ddrop = 35;
const int as_ddup = 36;
const int as_plus = 37;
const int as_inver = 38;
const int as_negat = 39;
const int as_dnega = 40;
const int as_subb = 41;
const int as_abss = 42;
const int as_equal = 43;
const int as_uless = 44;
const int as_less = 45;
const int as_ummod = 46;
const int as_msmod = 47;
const int as_slmod = 48;
const int as_mod = 49;
const int as_slash = 50;
const int as_umsta = 51;
const int as_star = 52;
const int as_mstar = 53;
const int as_ssmod = 54;
const int as_stasl = 55;
const int as_pick = 56;
const int as_pstor = 57;
const int as_dstor = 58;
const int as_dat = 59;
const int as_count = 60;
const int as_dovar = 61;
const int as_max = 62;
const int as_min = 63;
const int as_tone = 64; //
const int as_sendPacket = 65;
const int as_poke = 66;
const int as_peek = 67;
const int as_adc = 68;
const int as_pin = 69; //
const int as_duty = 70; //
const int as_freq = 71; //
const int as_gfx_init = 72;
const int as_screen_w = 73;
const int as_screen_h = 74;
const int as_cls = 75;
const int as_pixel = 76;
const int as_gfx_line = 77;
const int as_rect = 78;
const int as_fill_rect = 79;
const int as_text = 80;
const int as_text_w = 81;
const int as_rotation = 82;
const int as_touch_update = 83;
const int as_touch_type = 84;
const int as_touch_x = 85;
const int as_touch_y = 86;
const int as_touch_dx = 87;
const int as_touch_dy = 88;
const int as_touch_tick = 89;
const int as_touch_target = 90;
const int as_swipe_detect = 91;
const int as_style_new = 92;
const int as_style_set = 93;
const int as_style_field_get = 94;
const int as_style_field_set = 95;
const int as_node_new = 96;
const int as_node_add = 97;
const int as_node_remove = 98;
const int as_node_dirty = 99;
const int as_node_draw = 100;
const int as_node_draw_tree = 101;
const int as_node_hit = 102;
const int as_node_screen_xy = 103;
const int as_node_set_bounds = 104;
const int as_node_visible = 105;
const int as_node_touchable = 106;
const int as_node_field_get = 107;
const int as_node_field_set = 108;
const int as_event_dispatch = 109;
const int as_event_bubble = 110;
const int as_app_new = 111;
const int as_app_add_screen = 112;
const int as_app_next = 113;
const int as_app_prev = 114;
const int as_app_show = 115;
const int as_app_active = 116;
const int as_app_draw = 117;
const int as_w_panel = 118;
const int as_w_label = 119;
const int as_w_button = 120;
const int as_w_status = 121;
const int as_w_value = 122;
const int as_w_gauge = 123;
const int as_w_chart = 124;
const int as_w_alarm = 125;
